//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlvLesson11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlvTaiKhoan
    {
        public int Plvid { get; set; }
        public string PlvUserName { get; set; }
        public string PlvPassWord { get; set; }
        public string PlvFullName { get; set; }
        public Nullable<int> PlvAge { get; set; }
        public string PlvEmail { get; set; }
        public string PlvPhone { get; set; }
        public Nullable<bool> PlvStatus { get; set; }
    }
}
