//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLVBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plvKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plvKhoa()
        {
            this.PlvSinhViens = new HashSet<PlvSinhVien>();
        }
    
        public string PlvMaKh { get; set; }
        public string PlvTenKh { get; set; }
        public Nullable<bool> PlvTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlvSinhVien> PlvSinhViens { get; set; }
    }
}
